files:
  - source: /projects/pswg/src/main/resources/assets/pswg/lang/en_us.json
    translation: /projects/pswg/src/main/resources/assets/pswg/lang/%locale_with_underscore%.json
    skip_untranslated_strings: true
